name: ROSE Digital

markdown: redcarpet
redcarpet:
  extensions: ["smart", "no_intra_emphasis", "autolink", "tables", "space_after_headers", "superscript"]
pygments: true

paginate: 3
paginate_path: 'blog/page-:num'

social:
  github: rosedigital
  twitter: rosedgtl
  snapchat: rosedigital

authors:
  zac:
    name: Zac Colley
    display_name: Zac
    title: MS Paint Artist
    gravatar: 26ab7600fc89f94711ec3b7db40d039b
    email: zac@rosedigital.co.uk
    web: http://zaccolley.com
    twitter: zaccolley
    github: zaccolley
  peter:
    name: Peter Jones
    display_name: Peter
    title: SEO CEO
    gravatar: #
    email: peter@rosedigital.co.uk
    web: http://peterjones.io
    twitter: peterjonesio
    github: kephail