name: ROSE Digital · Web design and development in Portsmouth
url: http://rosedigital.co.uk
email: hello@rosedigital.co.uk
desc: 'ROSE Digital work with you to design and develop web applications.'
timezone: GMT

markdown: redcarpet
redcarpet:
  extensions: ['smart', 'no_intra_emphasis', 'autolink', 'tables', 'space_after_headers', 'superscript']
highlighter: rouge

include: ['.htaccess']

exclude: ['package.json', 'node_modules', 'gulpfile.js', 'README.md', 'LICENSE']

emoji-images-path: 'img/emojione-emoji/svg'