name: ROSE Digital
url: http://rosedigital.co.uk
email: hello@rosedigital.co.uk
desc: 'ROSE Digital | Portsmouth based Web Design, Web Development and Graphic Design'
timezone: GMT

markdown: redcarpet
redcarpet:
  extensions: ['smart', 'no_intra_emphasis', 'autolink', 'tables', 'space_after_headers', 'superscript']
pygments: true

paginate: 3
paginate_path: blog/page-:num

include: ['.htaccess']

exclude: ['scripts', 'stylesheets/', 'package.json', 'node_modules', 'bower.json', 'Gruntfile.js', 'README.md', 'LICENSE']

emoji-images-path: 'img/hangouts-emoji/'