name: ROSE Digital

markdown: redcarpet
redcarpet:
  extensions: ["smart", "no_intra_emphasis", "autolink", "tables", "space_after_headers", "superscript"]
pygments: true

paginate: 3
paginate_path: 'blog/page-:num'