name: ROSE Digital
url: http://rosedigital.co.uk
email: hello@rosedigital.co.uk
desc: 'ROSE Digital | Portsmouth based web design & development'
timezone: GMT

markdown: redcarpet
redcarpet:
  extensions: ['smart', 'no_intra_emphasis', 'autolink', 'tables', 'space_after_headers', 'superscript']
highlighter: rouge

paginate: 3
paginate_path: blog/page-:num

include: ['.htaccess']

exclude: ['package.json', 'node_modules', 'gulpfile.js', 'README.md', 'LICENSE']

emoji-images-path: 'img/hangouts-emoji/'